# Generated by Django 4.1.2 on 2022-10-08 14:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre_director/a', max_length=100)),
                ('last_name', models.CharField(help_text='Apellido_director/a', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_dead', models.DateField(blank=True, null=True, verbose_name='Died')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del género', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la película', max_length=100)),
                ('premiere', models.DateField(blank=True, null=True)),
                ('genre', models.ManyToManyField(to='data_directors.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta película', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('ob', 'on billboard'), ('os', 'on streaming'), ('oc', 'on cable tv')], default='ob', help_text='Disponiblilidad de la película', max_length=2)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_directors.movie')),
            ],
        ),
    ]
